Updated github actions

diff --git a/.github/workflows/Tests.yml b/.github/workflows/Tests.yml
--- a/.github/workflows/Tests.yml
+++ b/.github/workflows/Tests.yml
@@ -1,5 +1,5 @@
 # --------------------------------------------------------------------------------
-# This workflow was automatically generated by Action Status 1.0.2 (365).
+# This workflow was automatically generated by Action Status 2.0.6 (494).
 # (see https://actionstatus.elegantchaos.com for more details)
 # --------------------------------------------------------------------------------
 
@@ -11,7 +11,7 @@ jobs:
 
     macOS-swift-50:
         name: macOS (Swift 5.0)
-        runs-on: macOS-latest
+        runs-on: macos-10.15
         steps:
         - name: Checkout
           uses: actions/checkout@v1
@@ -19,13 +19,12 @@ jobs:
           run: mkdir logs
         - name: Xcode Version
           run: |
+            ls -d /Applications/Xcode*
             sudo xcode-select -s /Applications/Xcode_11.2.1.app
             xcodebuild -version
             swift --version
         - name: Swift Version
           run: swift --version
-        - name: Build (Release)
-          run: swift build -c release
         - name: Test (Release)
           run: swift test --configuration release -Xswiftc -enable-testing 
         - name: Upload Logs
@@ -38,9 +37,9 @@ jobs:
 
     macOS-swift-nightly:
         name: macOS (Swift Development Nightly)
-        runs-on: macOS-latest
         env:
             TOOLCHAINS: swift
+        runs-on: macos-11
         steps:
         - name: Checkout
           uses: actions/checkout@v1
@@ -49,7 +48,7 @@ jobs:
         - name: Install Toolchain
           run: |
             branch="development"
-            wget --quiet https://swift.org/builds/$branch/xcode/latest-build.yml
+            wget --quiet https://download.swift.org/$branch/xcode/latest-build.yml
             grep "download:" < latest-build.yml > filtered.yml
             sed -e 's/-osx.pkg//g' filtered.yml > stripped.yml
             sed -e 's/:[^:\/\/]/YML="/g;s/$/"/g;s/ *=/=/g' stripped.yml > snapshot.sh
@@ -58,7 +57,8 @@ jobs:
             wget --quiet https://swift.org/builds/$branch/xcode/$downloadYML/$downloadYML-osx.pkg
             sudo installer -pkg $downloadYML-osx.pkg -target /
             ln -s "/Library/Developer/Toolchains/$downloadYML.xctoolchain/usr/bin" swift-latest
-            sudo xcode-select -s /Applications/Xcode_12_beta.app
+            ls -d /Applications/Xcode*
+            sudo xcode-select -s /Applications/Xcode_13.2.1.app
             swift --version
         - name: Xcode Version
           run: |
@@ -66,10 +66,50 @@ jobs:
             xcrun swift --version
         - name: Swift Version
           run: swift --version
-        - name: Build (Release)
-          run: export PATH="swift-latest:$PATH"; swift build -c release
         - name: Test (Release)
-          run: export PATH="swift-latest:$PATH"; swift test --configuration release -Xswiftc -enable-testing --enable-test-discovery
+          run: export PATH="swift-latest:$PATH"; swift test --configuration release -Xswiftc -enable-testing 
+        - name: Upload Logs
+          uses: actions/upload-artifact@v1
+          if: always()
+          with:
+            name: logs
+            path: logs
+
+
+    linux-swift-50:
+        name: Linux (Swift 5.0)
+        runs-on: ubuntu-18.04
+        container: swift:5.0
+        steps:
+        - name: Checkout
+          uses: actions/checkout@v1
+        - name: Make Logs Directory
+          run: mkdir logs
+        - name: Swift Version
+          run: swift --version
+        - name: Test (Release)
+          run: swift test --configuration release -Xswiftc -enable-testing 
+        - name: Upload Logs
+          uses: actions/upload-artifact@v1
+          if: always()
+          with:
+            name: logs
+            path: logs
+
+
+    linux-swift-nightly:
+        name: Linux (Swift Development Nightly)
+        runs-on: ubuntu-18.04
+        container: swiftlang/swift:nightly
+        steps:
+        - name: Checkout
+          uses: actions/checkout@v1
+        - name: Make Logs Directory
+          run: mkdir logs
+        - name: Swift Version
+          run: swift --version
+        - name: Test (Release)
+          run: swift test --configuration release -Xswiftc -enable-testing 
         - name: Upload Logs
           uses: actions/upload-artifact@v1
           if: always()
@@ -79,8 +119,8 @@ jobs:
 
 
     xcode-swift-50:
-        name: Xcode (Swift 5.0)
-        runs-on: macOS-latest
+        name: iOS/tvOS/watchOS (Swift 5.0, Xcode 11.2.1)
+        runs-on: macos-10.15
         steps:
         - name: Checkout
           uses: actions/checkout@v1
@@ -88,6 +128,7 @@ jobs:
           run: mkdir logs
         - name: Xcode Version
           run: |
+            ls -d /Applications/Xcode*
             sudo xcode-select -s /Applications/Xcode_11.2.1.app
             xcodebuild -version
             swift --version
@@ -110,16 +151,55 @@ jobs:
             SCHEME="Localization-iOS"
             fi
             echo "set -o pipefail; export PATH='swift-latest:$PATH'; WORKSPACE='$WORKSPACE'; SCHEME='$SCHEME'" > setup.sh
-        - name: Build (iOS Release)
-          run: |
-            source "setup.sh"
-            echo "Building workspace $WORKSPACE scheme $SCHEME."
-            xcodebuild clean build -workspace "$WORKSPACE" -scheme "$SCHEME" -configuration Release CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | tee logs/xcodebuild-iOS-build-release.log | xcpretty
         - name: Test (iOS Release)
           run: |
             source "setup.sh"
             echo "Testing workspace $WORKSPACE scheme $SCHEME."
             xcodebuild test -workspace "$WORKSPACE" -scheme "$SCHEME" -destination "name=iPhone 11" -configuration Release CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ENABLE_TESTABILITY=YES | tee logs/xcodebuild-iOS-test-release.log | xcpretty
+        - name: Detect Workspace & Scheme (tvOS)
+          run: |
+            WORKSPACE="Localization.xcworkspace"
+            if [[ ! -e "$WORKSPACE" ]]
+            then
+            WORKSPACE="."
+            GOTPACKAGE=$(xcodebuild -workspace . -list | (grep Localization-Package || true))
+            if [[ $GOTPACKAGE != "" ]]
+            then
+            SCHEME="Localization-Package"
+            else
+            SCHEME="Localization"
+            fi
+            else
+            SCHEME="Localization-tvOS"
+            fi
+            echo "set -o pipefail; export PATH='swift-latest:$PATH'; WORKSPACE='$WORKSPACE'; SCHEME='$SCHEME'" > setup.sh
+        - name: Test (tvOS Release)
+          run: |
+            source "setup.sh"
+            echo "Testing workspace $WORKSPACE scheme $SCHEME."
+            xcodebuild test -workspace "$WORKSPACE" -scheme "$SCHEME" -destination "name=Apple TV" -configuration Release CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ENABLE_TESTABILITY=YES | tee logs/xcodebuild-tvOS-test-release.log | xcpretty
+        - name: Detect Workspace & Scheme (watchOS)
+          run: |
+            WORKSPACE="Localization.xcworkspace"
+            if [[ ! -e "$WORKSPACE" ]]
+            then
+            WORKSPACE="."
+            GOTPACKAGE=$(xcodebuild -workspace . -list | (grep Localization-Package || true))
+            if [[ $GOTPACKAGE != "" ]]
+            then
+            SCHEME="Localization-Package"
+            else
+            SCHEME="Localization"
+            fi
+            else
+            SCHEME="Localization-watchOS"
+            fi
+            echo "set -o pipefail; export PATH='swift-latest:$PATH'; WORKSPACE='$WORKSPACE'; SCHEME='$SCHEME'" > setup.sh
+        - name: Build (watchOS Release)
+          run: |
+            source "setup.sh"
+            echo "Building workspace $WORKSPACE scheme $SCHEME."
+            xcodebuild clean build -workspace "$WORKSPACE" -scheme "$SCHEME" -destination "name=Apple Watch Series 5 - 44mm" -configuration Release CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ENABLE_TESTABILITY=YES | tee logs/xcodebuild-watchOS-build-release.log | xcpretty
         - name: Upload Logs
           uses: actions/upload-artifact@v1
           if: always()
@@ -129,10 +209,10 @@ jobs:
 
 
     xcode-swift-nightly:
-        name: Xcode (Swift Development Nightly)
-        runs-on: macOS-latest
+        name: iOS/tvOS/watchOS (Swift Development Nightly, Xcode 13.2.1)
         env:
             TOOLCHAINS: swift
+        runs-on: macos-11
         steps:
         - name: Checkout
           uses: actions/checkout@v1
@@ -141,7 +221,7 @@ jobs:
         - name: Install Toolchain
           run: |
             branch="development"
-            wget --quiet https://swift.org/builds/$branch/xcode/latest-build.yml
+            wget --quiet https://download.swift.org/$branch/xcode/latest-build.yml
             grep "download:" < latest-build.yml > filtered.yml
             sed -e 's/-osx.pkg//g' filtered.yml > stripped.yml
             sed -e 's/:[^:\/\/]/YML="/g;s/$/"/g;s/ *=/=/g' stripped.yml > snapshot.sh
@@ -150,7 +230,8 @@ jobs:
             wget --quiet https://swift.org/builds/$branch/xcode/$downloadYML/$downloadYML-osx.pkg
             sudo installer -pkg $downloadYML-osx.pkg -target /
             ln -s "/Library/Developer/Toolchains/$downloadYML.xctoolchain/usr/bin" swift-latest
-            sudo xcode-select -s /Applications/Xcode_12_beta.app
+            ls -d /Applications/Xcode*
+            sudo xcode-select -s /Applications/Xcode_13.2.1.app
             swift --version
         - name: Xcode Version
           run: |
@@ -179,12 +260,51 @@ jobs:
           run: |
             source "setup.sh"
             echo "Building workspace $WORKSPACE scheme $SCHEME."
-            xcodebuild clean build -workspace "$WORKSPACE" -scheme "$SCHEME" -configuration Release CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | tee logs/xcodebuild-iOS-build-release.log | xcpretty
-        - name: Test (iOS Release)
+            xcodebuild clean build -workspace "$WORKSPACE" -scheme "$SCHEME" -destination "name=iPhone 11" -configuration Release CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ENABLE_TESTABILITY=YES | tee logs/xcodebuild-iOS-build-release.log | xcpretty
+        - name: Detect Workspace & Scheme (tvOS)
+          run: |
+            WORKSPACE="Localization.xcworkspace"
+            if [[ ! -e "$WORKSPACE" ]]
+            then
+            WORKSPACE="."
+            GOTPACKAGE=$(xcodebuild -workspace . -list | (grep Localization-Package || true))
+            if [[ $GOTPACKAGE != "" ]]
+            then
+            SCHEME="Localization-Package"
+            else
+            SCHEME="Localization"
+            fi
+            else
+            SCHEME="Localization-tvOS"
+            fi
+            echo "set -o pipefail; export PATH='swift-latest:$PATH'; WORKSPACE='$WORKSPACE'; SCHEME='$SCHEME'" > setup.sh
+        - name: Build (tvOS Release)
           run: |
             source "setup.sh"
-            echo "Testing workspace $WORKSPACE scheme $SCHEME."
-            xcodebuild test -workspace "$WORKSPACE" -scheme "$SCHEME" -destination "name=iPhone 11" -configuration Release CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ENABLE_TESTABILITY=YES | tee logs/xcodebuild-iOS-test-release.log | xcpretty
+            echo "Building workspace $WORKSPACE scheme $SCHEME."
+            xcodebuild clean build -workspace "$WORKSPACE" -scheme "$SCHEME" -destination "name=Apple TV" -configuration Release CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ENABLE_TESTABILITY=YES | tee logs/xcodebuild-tvOS-build-release.log | xcpretty
+        - name: Detect Workspace & Scheme (watchOS)
+          run: |
+            WORKSPACE="Localization.xcworkspace"
+            if [[ ! -e "$WORKSPACE" ]]
+            then
+            WORKSPACE="."
+            GOTPACKAGE=$(xcodebuild -workspace . -list | (grep Localization-Package || true))
+            if [[ $GOTPACKAGE != "" ]]
+            then
+            SCHEME="Localization-Package"
+            else
+            SCHEME="Localization"
+            fi
+            else
+            SCHEME="Localization-watchOS"
+            fi
+            echo "set -o pipefail; export PATH='swift-latest:$PATH'; WORKSPACE='$WORKSPACE'; SCHEME='$SCHEME'" > setup.sh
+        - name: Build (watchOS Release)
+          run: |
+            source "setup.sh"
+            echo "Building workspace $WORKSPACE scheme $SCHEME."
+            xcodebuild clean build -workspace "$WORKSPACE" -scheme "$SCHEME" -destination "name=Apple Watch Series 5 - 44mm" -configuration Release CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ENABLE_TESTABILITY=YES | tee logs/xcodebuild-watchOS-build-release.log | xcpretty
         - name: Upload Logs
           uses: actions/upload-artifact@v1
           if: always()
